"""58 legacy ops — each must exist as a graph node; execution via NativeOpRegistry."""

from __future__ import annotations

# Frozen list from Executor._dispatch (see tests/parity/test_ir_coverage.py)
LEGACY_OPS: tuple[str, ...] = (
    "Reply",
    "Ask",
    "Remember",
    "If",
    "Buttons",
    "InlineButton",
    "InlineKeyboard",
    "InlineKeyboardFromList",
    "InlineKeyboardFromDB",
    "Photo",
    "Sticker",
    "ForwardPhoto",
    "SaveFile",
    "StartScenario",
    "SendMarkdown",
    "SendHTML",
    "SendMarkdownV2",
    "SendDocument",
    "SendAudio",
    "SendVideo",
    "SendVoice",
    "SendLocation",
    "SendContact",
    "SendPoll",
    "SendInvoice",
    "SendGame",
    "DownloadFile",
    "Step",
    "EndScenario",
    "ReturnFromScenario",
    "RepeatStep",
    "GotoStep",
    "SaveToDB",
    "LoadFromDB",
    "HttpGet",
    "HttpPost",
    "Log",
    "Sleep",
    "TelegramAPI",
    "UseBlock",
    "RandomReply",
    "GlobalVar",
    "PhotoVar",
    "ForEach",
    "WhileLoop",
    "BreakLoop",
    "ContinueLoop",
    "Timeout",
    "Notify",
    "Broadcast",
    "CheckSubscription",
    "GetChatMemberRole",
    "ForwardMsg",
    "LoadJson",
    "ParseJson",
    "SaveJson",
    "DeleteFile",
    "DeleteDictKey",
    "SetDictKey",
    "HttpPatch",
    "HttpPut",
    "HttpDelete",
    "SetHttpHeaders",
    "FetchJson",
    "DeleteFromDB",
    "GetAllDBKeys",
    "SaveGlobalDB",
    "LoadFromUserDB",
    "ReturnValue",
    "CallBlock",
)

# Ops executed via graph control-flow, not registry statement body
GRAPH_CONTROL_OPS = frozenset({"If", "ForEach", "WhileLoop", "Noop", "StartScenario"})
