/* Autogenerated modules entrypoint. */
import type { ModuleDefinition, ModuleCategory } from './types';
import { BUILTIN_MODULE_CATEGORIES } from './builtin/index.ts';

export type { ModuleDefinition, ModuleCategory };
export { BUILTIN_MODULE_CATEGORIES };
export const BUILTIN_MODULE_LIST: ModuleDefinition[] = BUILTIN_MODULE_CATEGORIES.flatMap((category) => category.items);
export const BUILTIN_MODULES_BY_ID: Record<string, ModuleDefinition> = Object.fromEntries(
  BUILTIN_MODULE_LIST.map((item) => [item.id, item]),
);

export {
  GRAPH_MODULE_REGISTRY,
  GRAPH_MODULE_IDS,
  GRAPH_MODULE_SUITES,
  isGraphNativeModule,
  getGraphModule,
} from './graph/registry.js';
export { composeModules, previewComposeModules } from './composition/index.js';
export {
  classifyModule,
  buildModuleCatalog,
  MODULE_KIND,
  MODULE_BADGE,
} from './library/module_catalog.js';
export {
  runInsertionPreview,
  commitInsertion,
  runLegacyMigration,
  withAutoDependencies,
} from './library/module_insertion_pipeline.js';
export {
  migrateLegacyDslModule,
  dslCodeToStacks,
  manifestToGraphModuleJson,
} from './library/migrate_legacy_dsl.js';
export { analyzeGraphTopology, formatTopologySummary } from './library/topology_preview.js';

