import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const builtinRoot = path.join(repoRoot, 'src', 'modules', 'builtin');
const registryPath = path.join(builtinRoot, 'registry.ts');
const indexPath = path.join(repoRoot, 'src', 'modules', 'index.ts');

function readMeta(moduleDir) {
  const metaPath = path.join(moduleDir, 'meta.json');
  if (!fs.existsSync(metaPath)) return null;
  return JSON.parse(fs.readFileSync(metaPath, 'utf8'));
}

function readCode(moduleDir) {
  const indexTs = path.join(moduleDir, 'index.ts');
  if (!fs.existsSync(indexTs)) return '';
  const src = fs.readFileSync(indexTs, 'utf8');
  const m = src.match(/"code":\s*"((?:\\.|[^"\\])*)"/);
  if (!m) return '';
  return m[1].replace(/\\n/g, '\n').replace(/\\"/g, '"');
}

function main() {
  const dirs = fs.readdirSync(builtinRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const byCategory = new Map();
  for (const id of dirs) {
    const moduleDir = path.join(builtinRoot, id);
    const meta = readMeta(moduleDir);
    if (!meta?.id) continue;
    const code = readCode(moduleDir);
    const item = {
      id: meta.id,
      name: meta.name || id,
      desc: meta.desc || '',
      category: meta.category || 'Uncategorized',
      code,
    };
    const cat = item.category;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(item);
  }

  const categories = [...byCategory.entries()].map(([category, items]) => ({
    category,
    items: items.sort((a, b) => a.name.localeCompare(b.name)),
  }));

  const registryTs = `/* eslint-disable max-len */
/* Autogenerated built-in module registry. Do not edit manually. */

import type { ModuleCategory } from '../types';

export const BUILTIN_MODULE_CATEGORIES: ModuleCategory[] = ${JSON.stringify(categories, null, 2)} as ModuleCategory[];
`;

  fs.writeFileSync(registryPath, registryTs, 'utf8');
  fs.writeFileSync(indexPath, `/* Autogenerated modules entrypoint. */
import type { ModuleDefinition, ModuleCategory } from './types';
import { BUILTIN_MODULE_CATEGORIES } from './builtin/index.ts';

export type { ModuleDefinition, ModuleCategory };
export { BUILTIN_MODULE_CATEGORIES };
export const BUILTIN_MODULE_LIST: ModuleDefinition[] = BUILTIN_MODULE_CATEGORIES.flatMap((category) => category.items);
export const BUILTIN_MODULES_BY_ID: Record<string, ModuleDefinition> = Object.fromEntries(
  BUILTIN_MODULE_LIST.map((item) => [item.id, item]),
);

export {
  GRAPH_MODULE_REGISTRY,
  GRAPH_MODULE_IDS,
  GRAPH_MODULE_SUITES,
  isGraphNativeModule,
  getGraphModule,
} from './graph/registry.js';
export { composeModules, previewComposeModules } from './composition/index.js';
`, 'utf8');

  console.log(`Wrote ${categories.length} categories, ${dirs.length} modules`);
}

main();
