export {
  compilePhoto,
  compileVideo,
  compileAudio,
  compileSticker,
  compileContact,
  compileLocation,
  compilePoll,
  compileMedia,
  compileSendFile,
  compilePhotoVar,
  compileDocumentVar,
  compileDocumentSend,
  compileForwardMsg,
  compileBroadcast,
} from '../compileCore.js';
